#!/bin/bash
# Resets database and clears uploaded images

echo Clearing database image entries and reset id counter
sqlite3 db.sqlite3 "BEGIN; DELETE FROM api_image; UPDATE sqlite_sequence SET seq = 0 WHERE name='api_image'; COMMIT;"

echo Clearing user database
sqlite3 users.db "BEGIN; DELETE FROM users; COMMIT;"

echo Deleting stored images
rm images/*

echo Deleting name and embedding database
rm -rf database 

echo Replacing with default database
unzip database.zip
